/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
/**
 *
 * @author ferry
 */
public class about extends javax.swing.JInternalFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ig1 = new javax.swing.JLabel();
        ig = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_about_40px.png"))); // NOI18N
        jLabel1.setText("ABOUT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 270, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 790, 60));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APLIKASI KASIR WARUNGPANJAT");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 520, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 510, 20));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Universitas Indraprasta PGRI");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 300, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 280, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_information_120px.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 140));

        ig1.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N
        ig1.setForeground(new java.awt.Color(255, 255, 255));
        ig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_instagram_40px.png"))); // NOI18N
        ig1.setText("www.Instagram.com");
        ig1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ig1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ig1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ig1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ig1MouseExited(evt);
            }
        });
        jPanel3.add(ig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 240, 30));

        ig.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 18)); // NOI18N
        ig.setForeground(new java.awt.Color(255, 255, 255));
        ig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_facebook_old_40px.png"))); // NOI18N
        ig.setText("www.Facebook.com");
        ig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                igMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                igMouseExited(evt);
            }
        });
        jPanel3.add(ig, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 750, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ig1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig1MouseClicked
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.instagram.com").toURI());
            dispose();
        }catch(Exception ex){
            System.out.println(ex);

        }
    }//GEN-LAST:event_ig1MouseClicked

    private void ig1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig1MouseEntered
        // TODO add your handling code here:
        ig1.setForeground(Color.blue);
    }//GEN-LAST:event_ig1MouseEntered

    private void ig1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig1MouseExited
        // TODO add your handling code here:
        ig1.setForeground(Color.black);
    }//GEN-LAST:event_ig1MouseExited

    private void igMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igMouseClicked
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.Facebook.com").toURI());
            dispose();
        }catch(Exception ex){
            System.out.println(ex);

        }
    }//GEN-LAST:event_igMouseClicked

    private void igMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igMouseEntered
        // TODO add your handling code here:
        ig.setForeground(Color.blue);
    }//GEN-LAST:event_igMouseEntered

    private void igMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igMouseExited
        // TODO add your handling code here:
        ig.setForeground(Color.black);
    }//GEN-LAST:event_igMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ig;
    private javax.swing.JLabel ig1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
